### PR TITLE
Disable `time` features

### PR DESCRIPTION
**Pull request by lnicola**
I left these enabled in `dev-dependencies`, so that the tests still work, but to be honest, I don't think those tests are really useful.

The reason to disable this is the proc macro stuff has a significant build time impact, and it's not really something `zip` users need.

### CODE REVIEW

**Comment by zamazan4ik** [comment]
@Plecra we need your opinion here.

**Review by Plecra — CHANGES_REQUESTED** [review]
Argh, more compatibility hazards. Fine, it's worth it. Hopefully we won't run into compatibility hazards, though I'd like to use a changelog to help users upgrading to the new version.

**Comment by Plecra** [comment]
Hmm, I'm not sure about standard ways to to this, but I can pop a `CHANGELOG.md` in the root.

**Review by Plecra — APPROVED** [review]

**Comment by Plecra** [comment]
Oops! We've got a bug in the fuzz CI. You'll need to add `"std"` to the featureset for `time`, otherwise we can't get the current time.

**Comment by Plecra** [comment]
(That's https://docs.rs/time/latest/time/struct.OffsetDateTime.html#method.now_utc btw - it mentions the feature dep)

**Comment by Plecra** [comment]
We need it for release `dependencies` too :) the `now_utc` API is used for writing the current time in file metadata.

**Comment by lnicola** [comment]
Ah, okay. Fixed.

**Review by Plecra — APPROVED** [review]
LGTM! Thanks a bunch

**Comment by lnicola** [comment]
Thanks! Do you think you'll cut out a new release soon?

**Comment by Plecra** [comment]
Just after addressing the CVE issue, yep!

**Pull request merged**
