### PR TITLE
Depend Fix [zstd]

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
when compiling with Actix web the exact version depend 0.11.0 creates a conflict with actix-web

By setting it to just 0.11 it can use any patch version of 0.11 so 0.11.0 or 0.11... 

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio

### CODE REVIEW

**Comment by danylaporte** [comment]
I have run into the conflict version with actix-web. Is it possible to fix the clippy issues and merge the pull request?

**Comment by wyatt-herkamp** [comment]
> I have run into the conflict version with actix-web. Is it possible to fix the clippy issues and merge the pull request?

So the clippy breaks are just related to new clippy rules nothing I changed. However they should be fixed now

**Comment by Heliozoa** [comment]
` zstd = { version = "0.11", optional = true }` and ` zstd = { version = "0.11.0", optional = true }` are the exact same from Cargo's perspective because Cargo (mostly) follows [SemVer](https://semver.org/). `0.11.0` already allows use of any `0.11.z` patch release.

The problem is that the latest *release* of zip, 0.6.2, still uses zstd 0.10: https://crates.io/crates/zip/0.6.2/dependencies

**Comment by wyatt-herkamp** [comment]
> ` zstd = { version = "0.11", optional = true }` and ` zstd = { version = "0.11.0", optional = true }` are the exact same from Cargo's perspective because Cargo (mostly) follows [SemVer](https://semver.org/). `0.11.0` already allows use of any `0.11.z` patch release.
> 
> The problem is that the latest _release_ of zip, 0.6.2, still uses zstd 0.10: [crates.io/crates/zip/0.6.2/dependencies](https://crates.io/crates/zip/0.6.2/dependencies)

That's what I had thought. I will revert that file change and keep the pr open as a clippy warning fix

**Pull request closed without merging**
