### PR TITLE
Add SUPPORTED_COMPRESSION_METHODS constant

### PR DESCRIPTION
**Pull request by kauhat**
This PR adds a `zip::SUPPORTED_METHODS` const to get the implemented compression methods at runtime.

I couldn't figure out how to use the existing `src/compression.rs test::methods()` function from tests/, so exposing this could be useful. I'm not certain that it should be publically exposed though, so perhaps this should be `pub(crate)` instead?

I am not a pro Rust dev so I'm not sure if this PR is following best practices, however, Clippy doesn't see any problems.

Added for #272

### CODE REVIEW

**Comment by kauhat** [comment]
Perhaps `CompressionMethod::iter()` would work better instead?

**Comment by Plecra** [comment]
I suppose it's reasonable to make this a public API. It could be useful for users. I'd like to have `zip::{read, write}::SUPPORTED_COMPRESSION_METHODS`

**Comment by zamazan4ik** [comment]
@kauhat can you update the PR regarding the @Plecra comment? Thanks!

**Comment by kauhat** [comment]
I have updated the name to `SUPPORTED_COMPRESSION_METHODS`. It's passing all tests with recent changes from the master branch.

**Review by zamazan4ik — APPROVED** [review]

**Pull request merged**
