### PR TITLE
feat: add Zstandard compression

### PR DESCRIPTION
**Pull request by zamazan4ik**
- add dependency on zstd crate
- add zstd feature to Cargo.toml
- update README
- update example with Zstd
- add Zstd support to the library

Notes:
- This work is mainly based on this original PR: https://github.com/zip-rs/zip/pull/240

Tested:
- During the development of the original PR

### CODE REVIEW

**Comment by zamazan4ik** [comment]
I decided to create another PR for Zstd since I think this functionality can be quite important for our users and the original PR author doesn't continue work on it (I've checked the original repository). The original work is pretty helpful and I think for me is left just a polishing: maybe add some missing documentation, tests, examples, maybe benchmarks. I suggest continuing working on this feature in this PR.

As the next steps, I am going to put work from this PR draft: https://github.com/kauhat/zip-rs/pull/1 into this PR as well.

**Comment by Plecra** [comment]
LGTM. The integration tests could be run with the different compression methods to make sure they're covered in CI. 

https://github.com/zip-rs/zip/blob/82cb91788306e040e6282a1c13174b94bd0c3b58/tests/end_to_end.rs#L12-L15

**Review by Plecra — APPROVED** [review]

**Comment by msuiche** [comment]
@zamazan4ik What utility do you recommend to decompress zstd zip files? When I use it all the default decompression tools I have say "Unsupported compression method"

**Comment by Plecra** [comment]
@msuiche In the original PR, it looks like the author tested interoperation with https://github.com/mcmilk/7-Zip-zstd . Do let me know if you find any concrete usages of the zstd method in the wild!

**Pull request merged**
