### PR TITLE
Test all compression methods in end to end test

### PR DESCRIPTION
**Pull request by kauhat**
This PR uses all available compression methods in the `end_to_end()` `copy()` and `append()` tests.

Depends on the SUPPORTED_METHODS constant added by #271.

```
> cargo test --nocapture

...


running 3 tests
Writing file with Stored compression
Checking file contents
Writing file with Deflated compression
Checking file contents
Writing file with Bzip2 compression
Checking file contents
Writing file with Zstd compression
Checking file contents
test end_to_end ... ok
test copy ... ok
test append ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

### CODE REVIEW

**Review by Plecra — APPROVED** [review]
LGTM. We can move the constant before the release.

**Comment by zamazan4ik** [comment]
@kauhat could you fix the fmt and clippy checkers, please? Thanks!

**Comment by kauhat** [comment]
A little more still to do on this, and I'll update #271 later tonight.

**Comment by Plecra** [comment]
Are you going to be able to wrap this up @kauhat ?

**Comment by kauhat** [comment]
I have updated this PR with changes from #271 and it is passing all tests. The clippy and fmt warnings should be resolved.

I haven't added `CompressionMethod::Aes` to the `SUPPORTED_COMPRESSION_METHODS` as it is read-only.

**Comment by kauhat** [comment]
I've also added some comments to the end to end test and updated some of the helper function names.

**Pull request merged**
