### PR TITLE
feat: migrate to Criterion

### PR DESCRIPTION
**Pull request by zamazan4ik**
- get rid of bencher since it's outdated and is not updated anymore
- add more benches from https://github.com/kauhat/zip-rs/pull/1/
- add strum for enum enumeration

Tested:
- Local bench runs

### CODE REVIEW

**Comment by zamazan4ik** [comment]
@Plecra maybe will be better to avoid using `strum` here and construct an array of supported algorithms manually? Maybe smth like this https://github.com/kauhat/zip-rs/pull/1/files#diff-72de9ea1c97e4bb5074ece721c16c233aa29d6068cae340f32fb3801ba18c4aeR125 or anything else

**Comment by Plecra** [comment]
Nice catch with the old dependencies. I think we might as well remove the benchmark code - the results aren't useful because of how non-deterministic they are, and we haven't given much of any focus to performance.

**Comment by zamazan4ik** [comment]
@kauhat maybe you have some comments regarding this PR? Since this work is mostly based on your prev PR.

**Comment by zamazan4ik** [comment]
I cannot say that the current benchmark code is useless. I think it could be used for future developments. E.g. for some changes, we really can check that we don't affect the performance a lot (or maybe even improved).

**Comment by kauhat** [comment]
Hi, thanks for looking at this! I think I had made some progress and was looking into seeding Lorem text into a memory buffer before getting stuck somewhere and distracted by other things.

I planned to write a handful of benchmarks covering simple use-cases (e.g. mirroring the /examples) and test against all compression methods with a few sets of test data, for example:

- Many small files
- A few large files
- Lorem Ipsumm/text data
- Binary data

The goal was to have a place to compare the performance of the compressor implementations. Although results will be different per machine, the relative speeds between the compression methods should be somewhat comparable and we have some expectations of how fast they should be. So if new compression methods are added maybe it would be visible if one is performing uncharacteristically. I don't have much experience writing benchmarks though. 😄 

Criterion was nice to use and it looks like there are some [hooks we could plug into for profiling](https://www.jibbow.com/posts/criterion-flamegraphs/) if anyone needs to do that. Perhaps this would make issues like #243 easier to diagnose.

Potentially we could set up an action to run benchmarks on `master` commits so that we have some historical record of performance and can be notified of regressions. 

I'm aware that zip-rs has many users - so I don't want to add any extra dependencies to the main code path. Could Criterion and any others be made optional under a feature?

**Comment by zamazan4ik** [comment]
Thanks for the intention to write some benchmarks!

> I'm aware that zip-rs has many users - so I don't want to add any extra dependencies to the main code path. Could Criterion and any others be made optional under a feature?

I don't think that it's problem - Criterion is `dev-dependency` so it shouldn't affect our users

**Comment by Plecra** [comment]
I am not planning to work on performance of this version of the crate, as I am not pushing quickly towards the 0.10 release. The benchmarking strategies are sure to be very useful though, so we'll be reusing the changes made in this PR in the next PR on this subject

**Pull request closed without merging**
