### PR TITLE
fix: permissions are not copied

### PR DESCRIPTION
**Pull request by zamazan4ik**
- fix a small bug when permissions where not copied

Tested:
- No

### CODE REVIEW

**Comment by zamazan4ik** [comment]
Fixes https://github.com/zip-rs/zip/issues/252

**Review by Plecra — APPROVED** [review]

**Comment by Plecra** [comment]
I wonder if we could make this easier to catch in future reviews, or just need to remember. Would `#[must_use]` on `FileOptions` do it?

**Comment by zamazan4ik** [comment]
Maybe this thread will be helpful for us: https://github.com/rust-lang/rust/issues/48926

**Comment by zamazan4ik** [comment]
Maybe another option is divide this struct into `FileOptions` and `FileOptionsBuilder` or smth like that

**Comment by Plecra** [comment]
Ah, you're right, that issue does help. We ought to just add `must_use` to each of the methods on `FileOptions`. Then, it's alright for other functions to return an ignored `FileOptions`. Can you add that in this PR please?

**Comment by zamazan4ik** [comment]
Sure, will do it

**Comment by zamazan4ik** [comment]
Done for all methods, except `default`.

**Pull request merged**
